apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.x.x.x-10.x.x.x <allocated IP address range>
      - 10.x.x.x-10.x.x.x <allocated IP address range>
