apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.x.x.x-10.x.x.x <allocated IP address range>
  - 10.x.x.x-10.x.x.x <allocated IP address range>
